### ISSUE TITLE
Actualizar tabla clientes

### ISSUE THREAD

**Issue by jcapoduri** [jcapoduri/neodymium#43]
- Actualizar DB:
  - agregar vinculacion con un plan de cuentas
  - agregar CUIT
  - agregar numero de ingresos brutos
  - agregar vinculacion con condicion frente al IVA 
- Actualizar modelo:
- Actualizar CRUD  controller
- _optional_ actualizar la UI

**Comment by Valentind88** [comment]
Falta agregar numero de ingresos brutos
