### ISSUE TITLE
Anular Facturas

### ISSUE THREAD

**Issue by jcapoduri** [jcapoduri/neodymium#68]

**Comment by Valentind88** [comment]
- Agregar booleano en invoice (anulada o no)
- Agregar booleano en invoice (impresa o no)

**Comment by Valentind88** [comment]
Ya estan agregados los 2 booleanos a schema, me faltaria ver donde y cuando haces las respectivas verificaciones

**Comment by jcapoduri** [comment]
Publica el branch asi lo puedo ver.
El print tenes un manager que lo hace, podes meterle ahi que cuando imprime, actualice el booleano a true de impreso
el de anular funciona en cualquier momento, y no podes imprimir si esta anulado
las restricciones de UI las hago yo si queres o te explico cuando tengas lo otro hecho
